JNG-4839 Java 11 to 17
BlackBeltTechnology/karaf-features pull request #32
Opened 2023-05-15 13:17 UTC by gaborflorian

JNG-4839 Java 11 to 17

2023-05-16 12:14 UTC, bencegelei approved these changes

2023-05-16 12:16 UTC, bencegelei approved these changes

2023-05-16 14:55 UTC, Madmat8 approved these changes

2023-05-16 15:01 UTC, noherczeg requested changes
```xml
 <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.10.1</version>
                    <configuration>
                        <source>11</source>
                        <target>11</target>
                    </configuration>
                </plugin>
```

FIxed

2023-05-16 15:37 UTC, robertcsakany requested changes
Please fix

2023-05-17 00:50 UTC, noherczeg approved these changes

2023-05-17 06:57 UTC, merged